import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* Start of bbruhinc Zendesk Widget script */}
        <Script
          id="ze-snippet"
          src="https://static.zdassets.com/ekr/snippet.js?key=d55949d1-a86e-4412-b691-4d5f5a490137"
          strategy="afterInteractive"
        />
        {/* End of bbruhinc Zendesk Widget script */}
      </body>
    </html>
  );
}
